name: Run tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
      - name: Download miseq demo dataset
        run: |
          wget https://github.com/Illumina/interop/releases/download/v1.0.6/MiSeqDemo.zip
          unzip MiSeqDemo.zip -d tests/data/
      - name: Run tests with pytest
        run: |
          pip install pytest
          pip install pytest-cov pylint
          python -m pytest tests --doctest-modules -o junit_family=xunit2 \
            --junitxml=junit/test-results.xml \
            --cov=bin tests/ --cov-report xml:junit/coverage.xml

  integration-test:
    runs-on: ubuntu-latest
    env:
      NXF_ANSI_LOG: 0
      NXF_VER: 20.10.0
    steps:
      - uses: actions/checkout@v1
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Download miseq demo dataset
        run: |
          wget https://github.com/Illumina/interop/releases/download/v1.0.6/MiSeqDemo.zip
          unzip MiSeqDemo.zip
      - name: Test Pipeline
        run: |
          nextflow run main.nf -c nextflow.config -profile testing -w work/ -with-docker ubuntu:latest --runDir MiSeqDemo/ --reportsDir output
          ls -l output/
          test -f output/run_metrics.json
          test -f output/percent_base.svg
          cat output/run_metrics.json

